# Generated by Django 2.0.3 on 2020-01-28 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(help_text='Price in $')),
            ],
        ),
        migrations.CreateModel(
            name='Euser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(help_text='Price in $')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=64)),
                ('pizza_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('price', models.IntegerField(help_text='Price in $')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(help_text='Price in $')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_articles', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dinners', models.ManyToManyField(to='orders.Dinner')),
                ('euser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Euser')),
                ('pastas', models.ManyToManyField(to='orders.Pasta')),
                ('pizzas', models.ManyToManyField(to='orders.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(help_text='Price in $')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='subs',
            field=models.ManyToManyField(to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(default='Cheese', to='orders.Topping'),
        ),
    ]
